name: lfkrebs
favicon: null
layout_spectrum: 0
typography_spectrum: 0.76186
title: Lutz F. Krebs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#91972a'
    - '#b6c454'
    - '#f6fedb'
    - '#3e2d54'
    - '#67672a'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
